### ISSUE TITLE
Add go.mod

### ISSUE THREAD

**Issue by BenLubar** [go-fed/apcore#1]
Should be as simple as `go mod init`

This way, you can guarantee that a specific version of, for example, go-fed is used.

**Comment by cjslep** [comment]
Dangit Ben has anyone told you, that you're too dang fast?

**Comment by cjslep** [comment]
996d1ee71b59a137e5d68fbe68dfe733e4df077f

I created a *whole* directory outside my GOPATH just so I could run the module commands. Man, life's tough. :P
