### ISSUE TITLE
Tie Application interface to OAuth login redirect

### ISSUE THREAD

**Issue by cjslep** [go-fed/apcore#19]

**Comment by aschrijver** [comment]
Is it an idea to have a separate `oauth2` library, similar to how `httpsig` is separated. It could have Mastodon compatibility and may (Solid) OIDC as well.

**Comment by cjslep** [comment]
Not a separate oauth2 library, no. It's already done: `apcore` uses an `oauth2` server-side library.

As per the recent refactor, I will need to revisit this issue.

**Comment by cjslep** [comment]
While fleshing out the endpoints in ea8c804eac12566c38ab6bea6a06cd59a6d84a44, I think this issue is obsolete.
